[project]
name = "colorsource.py"
version = "0.1.0"
description = "Open-source reimplementation of show file logic from the ETC Colorsource lightboards"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []
